language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly
      if: branch != master

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_success:
  - bash ci/after-success.sh

after_script: set +e

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
