[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std"]
description = "Real Time For the Masses (RTFM) framework for ARM Cortex-M microcontrollers"
documentation = "https://docs.rs/cortex-m-rtfm"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.2.2"

[dependencies]
cortex-m = "0.3.1"
untagged-option = "0.1.1"
rtfm-core = "0.1.0"
cortex-m-rtfm-macros = "0.2.1"

[target.'cfg(target_arch = "x86_64")'.dev-dependencies]
compiletest_rs = "0.2.8"

[dev-dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.3"

[dev-dependencies.stm32f103xx]
features = ["rt"]
version = "0.7.5"

[profile.release]
lto = true
