[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "cortex-m-srp"
version = "0.1.0"

[dependencies]
cortex-m = "0.2.0"

[dependencies.vcell]
features = ["const-fn"]
version = "0.1.0"