[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std"]
description = "Real Time For the Masses (RTFM), a framework for building concurrent applications, for ARM Cortex-M microcontrollers"
documentation = "https://docs.rs/cortex-m-rtfm"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.2.0"

[dependencies]
cortex-m = "0.3.1"
static-ref = "0.2.0"

[dependencies.cortex-m-rtfm-macros]
path = "macros"

[dev-dependencies]
compiletest_rs = "0.2.8"
stm32f103xx = "0.7.1"
