[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
build = "build.rs"
name = "cortex-m-rtfm"
version = "0.1.0"

[build-dependencies]
quote = "0.3.15"
syn = "0.11.10"

[dependencies]
cortex-m = "0.2.4"
static-ref = "0.1.0"
typenum = "1.7.0"

[dev-dependencies]
compiletest_rs = "0.2.5"

[features]
# Number of priority bits
P2 = []
P3 = []
P4 = []
P5 = []
default = ["P4"]
