[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "cortex-m-srp"
version = "0.1.0"

[build-dependencies]
quote = "0.3.15"
syn = "0.11.10"

[dependencies]
cortex-m = "0.2.2"
typenum = "1.7.0"
static-ref = { git = "https://github.com/japaric/static-ref" }

[dev-dependencies]
compiletest_rs = "0.2.5"

[features]
# Number of priority bits
P2 = []
P3 = []
P4 = []
P5 = []
default = ["P4"]
